version: '3.8'

services:
  basededatos:
    image: mariadb:latest
    container_name: basededatos
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql

  
   
      
volumes:
  mariadb_data:
  